name: Update spec JSON
on:
  schedule:
    - cron: '0 9 * * *'
jobs:
  update_spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Update OpenAPI JSON
        run: |
          curl https://api.youneedabudget.com/papi/spec-v1-swagger.json > spec-v1-swagger.json
      # Not using setup-java action b/c we really don't care what java version, just that it's new
      # If it ever turns out openapi generator isn't compatible with the newest java, we can
      # switch to using the action.
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y default-jdk-headless wget
      - name: Install and run OpenApi generator
        run: |
          mkdir -p ~/bin/openapitools
          curl https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh > ~/bin/openapitools/openapi-generator-cli
          chmod u+x ~/bin/openapitools/openapi-generator-cli
          export PATH=$PATH:~/bin/openapitools/
          rm -rf docs test ynab
          OPENAPI_GENERATOR_VERSION=4.2.2 openapi-generator-cli generate -g python -i spec-v1-swagger.json -c openapi.yaml
      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v1.5.0
        env:
          COMMIT_MESSAGE: "[Automated] Update openapi-generator-cli and swagger spec"
          PULL_REQUEST_TITLE: "[Automated] Update openapi-generator-cli and swagger spec"
          PULL_REQUEST_LABELS: "automated"
          PULL_REQUEST_REVIEWERS: "davidhao3300"
          # TODO: Supply a different github token so that the PR will trigger future github actions.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_SUFFIX: none
          PULL_REQUEST_BRANCH: automated/openapi-spec-update
